services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
      - type: volume
        source: next-app-node_modules
        target: /usr/src/app/next-app/node_modules
    networks:
      - microfrontends
    command: ["npm", "run", "dev"]
volumes:
  next-app-node_modules:
    driver: local
    name: next-app-node_modules
networks:
  microfrontends:
    external: true